name: Sync to Hugging Face hub

on:
schedule:
    - cron: '0 12 * * *' # Run every day at noon
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Robzy:$HF_TOKEN@huggingface.co/spaces/Robzy/hbg-weather main
